- name: Generate {{ specs.service }} deployment manifest
  ansible.builtin.template:
    src: "{{ specs.manifest_file }}"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/Deployments/{{ specs.service }}.yaml"
    mode: "0600"
  register: copy_manifest

- name: Generate {{ specs.service }} Quadlet file
  ansible.builtin.template:
    src: "{{ specs.kube_file }}"
    dest: "/etc/containers/systemd/{{ specs.service }}.kube"
    mode: "0600"
  register: copy_systemd_file

- name: Add systemd timer for {{ specs.service }}
  when: specs.timer is defined
  ansible.builtin.template:
    src: systemd/timer.j2
    dest: "{{ tpa_single_node_systemd_directory + '/' + specs.service }}.timer"
    mode: "0600"
  register: copy_systemd_timer_file

- name: Restart Podman Service for {{ specs.service }}
  ansible.builtin.systemd:
    state: "{{ specs.state }}"
    enabled: true
    daemon_reload: true
    name: "{{ specs.service }}"
    no_block: true
  when: copy_manifest.changed or copy_systemd_file.changed or copy_systemd_timer_file.changed
