---
- name: Set a variable about Rhel
  ansible.builtin.set_fact:
    rhel: false

- name: Set a variable if is a Rhel as expected
  ansible.builtin.set_fact:
    rhel: true
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'
    - (ansible_facts['distribution_version'] | split('.'))[1] | int >= 3

- name: Install Operating System Components
  ansible.builtin.include_tasks: os.yml
  when: rhel
  args:
    apply:
      become: true

- name: Execute Podman Actions
  ansible.builtin.include_tasks: podman.yml
  when: rhel
  args:
    apply:
      become: true
  vars:
    tpa_single_node_registry_username: "{{ lookup('env', 'TPA_SINGLE_NODE_REGISTRY_USERNAME') }}"
    tpa_single_node_registry_password: "{{ lookup('env', 'TPA_SINGLE_NODE_REGISTRY_PASSWORD') }}"

# 1 Configuring external services, DB, SSO, SQS, S3
- name: Configure infra dependencies
  ansible.builtin.include_tasks: infra/main.yml
  args:
    apply:
      become: true

# Step 4, 6 and 7
- name: Configure and deploy Guac
  ansible.builtin.include_tasks: guac/main.yml
  args:
    apply:
      become: true

# Step 5
- name: Configure/Deploy v11y walker
  ansible.builtin.include_tasks: v11y/walker.yml
  args:
    apply:
      become: true

# Step 8
- name: Configure/Deploy v11y api
  ansible.builtin.include_tasks: v11y/api.yml
  args:
    apply:
      become: true

# Step 10
- name: Configure/Deploy bombastic api
  ansible.builtin.include_tasks: bombastic/api.yml
  args:
    apply:
      become: true

# Step 9
- name: Configure/Deploy v11y Indexer
  ansible.builtin.include_tasks: v11y/indexer.yml
  args:
    apply:
      become: true

# Step 11
- name: Configure/Deploy Guac collector for bombastic
  ansible.builtin.include_tasks: guac/bombastic_collector.yml
  args:
    apply:
      become: true

# Step 12
- name: Configure/Deploy bombastic Indexer
  ansible.builtin.include_tasks: bombastic/indexer.yml
  args:
    apply:
      become: true

# Step 13
- name: Configure/Deploy bombastic Walker
  ansible.builtin.include_tasks: bombastic/walker.yml
  args:
    apply:
      become: true

# Step 14
- name: Configure/Deploy collector osv
  ansible.builtin.include_tasks: collector/osv.yml
  args:
    apply:
      become: true

# Step 15
- name: Configure/Deploy collectorist api
  ansible.builtin.include_tasks: collectorist/api.yml
  args:
    apply:
      become: true

# Step 17
- name: Configure/Deploy Guac vexination collector
  ansible.builtin.include_tasks: guac/vexination_collector.yml
  args:
    apply:
      become: true

# Step 16
- name: Configure/Deploy vexination api
  ansible.builtin.include_tasks: vexination/api.yml
  args:
    apply:
      become: true

# Step 18
- name: Configure/Deploy vexination Indexer
  ansible.builtin.include_tasks: vexination/indexer.yml
  args:
    apply:
      become: true

# Step 19
- name: Configure/Deploy vexination Walker
  ansible.builtin.include_tasks: vexination/walker.yml
  args:
    apply:
      become: true

# Step 22
- name: Configure/Deploy spog api
  ansible.builtin.include_tasks: spog/api.yml
  args:
    apply:
      become: true
