---
- name: Podman login to registry.redhat.io
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'
  ansible.builtin.command: podman login registry.redhat.io -u {{ tpa_single_node_registry_username }} --password {{ tpa_single_node_registry_password }}
  register: podman_login_result
  changed_when: '"Already logged in" not in podman_login_result'

- name: Create Manifests/Configs Directory
  ansible.builtin.file:
    state: directory
    dest: "{{ item }}"
    mode: "0700"
  loop:
    - "{{ tpa_single_node_kube_manifest_dir }}"
    - "{{ tpa_single_node_kube_configmap_dir }}"
    - "{{ tpa_single_node_certs_dir }}"

- name: Create RHTPA network
  containers.podman.podman_network:
    name: "{{ tpa_single_node_podman_network }}"

- name: Pull trustification image from registry.redhat.io
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'
  containers.podman.podman_image:
    name: "{{ tpa_single_node_trustification_image }}"


- name: Pull Guac image from registry.redhat.io
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'
  containers.podman.podman_image:
    name: "{{ tpa_single_node_guac_image }}"

 # 1 Configuring external services, DB, SSO, SQS, S3

# @postgres-remove
- name: Configure/Deploy Postgres
  ansible.builtin.include_tasks: podman/postgresql.yml

# SQS
# S3
# SSO

# 2 Init DB for Guac
- name: Configure/Deploy guac init
  ansible.builtin.include_tasks: podman/init_guac.yml

# 3 V11y Walker deployment and cronjob
- name: Configure/Deploy v11y walker
  ansible.builtin.include_tasks: podman/v11y_walker.yml

- name: Provision Guac collectsub
  ansible.builtin.include_tasks: podman/guac_collectsub.yml
