---
- name: Check Registry Username exists
  ansible.builtin.assert:
    that:
      - tpa_single_node_registry_username is defined
    fail_msg: "tpa_single_node_registry_username is not exists, export the registry username and password"

- name: Podman login to registry.redhat.io
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'
  ansible.builtin.command: podman login registry.redhat.io -u {{ tpa_single_node_registry_username }} -p {{ tpa_single_node_registry_password }}
  register: podman_login_result
  changed_when: '"Already logged in" not in podman_login_result'

- name: Create Manifests/Configs Directory
  ansible.builtin.file:
    state: directory
    dest: "{{ item }}"
    mode: "0700"
  loop:
    - "{{ tpa_single_node_kube_manifest_dir }}"

- name: Create RHTPA network
  containers.podman.podman_network:
    name: "{{ tpa_single_node_podman_network }}"

- name: Pull trustification image from registry.redhat.io
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'
  containers.podman.podman_image:
    name: "{{ tpa_single_node_trustification_image }}"

- name: Pull Guac image from registry.redhat.io
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'
  containers.podman.podman_image:
    name: "{{ tpa_single_node_guac_image }}"

  # 1 Configuring external services, DB, SSO, SQS, S3

# @postgres-remove
- name: Configure/Deploy Postgres
  ansible.builtin.include_tasks: podman/postgresql.yml

# SQS
# S3
# SSO

# 2 Init DB for Guac
- name: Configure/Deploy guac init
  ansible.builtin.include_tasks: podman/init_guac.yml

# 3 V11y Walker
- name: Configure/Deploy v11y walker
  ansible.builtin.include_tasks: podman/v11y_walker.yml

# 4 Guac Collectsub
- name: Provision Guac collectsub
  ansible.builtin.include_tasks: podman/guac_collectsub.yml
  vars:
    tpa_single_node_guac_csub_tls_cert_pem: "{{ lookup('file', tpa_single_node_guac_csub_tls_cert_pem_path) }}"
    tpa_single_node_guac_csub_tls_cert_key: "{{ lookup('file', tpa_single_node_guac_csub_tls_cert_key_path) }}"

# 5 Guac Graphql
- name: Provision Guac graphql
  ansible.builtin.include_tasks: podman/guac_graphql.yml
  vars:
    tpa_single_node_guac_graphql_tls_cert_pem: "{{ lookup('file', tpa_single_node_guac_graphql_tls_cert_pem_path) }}"
    tpa_single_node_guac_graphql_tls_cert_key: "{{ lookup('file', tpa_single_node_guac_graphql_tls_cert_key_path) }}"

# 6 V11y api
- name: Configure/Deploy v11y api
  ansible.builtin.include_tasks: podman/v11y_api.yml
