---
- name: Check Registry Username exists
  ansible.builtin.assert:
    that:
      - tpa_single_node_registry_username is defined
      - tpa_single_node_registry_username !=""
    fail_msg: "tpa_single_node_registry_username doesn't exist, export the registry username and password"

- name: Podman login to registry.redhat.io
  when: rhel
  ansible.builtin.command: podman login registry.redhat.io -u {{ tpa_single_node_registry_username }} -p {{ tpa_single_node_registry_password }}
  register: podman_login_result
  changed_when: '"Already logged in" not in podman_login_result'

- name: Create Manifests/Configs Directory
  ansible.builtin.file:
    state: directory
    dest: "{{ item }}"
    mode: "0700"
  loop:
    - "{{ tpa_single_node_kube_manifest_dir }}"

- name: Create RHTPA network
  containers.podman.podman_network:
    name: "{{ tpa_single_node_podman_network }}"

- name: Pull trustification image from registry.redhat.io
  when: rhel
  containers.podman.podman_image:
    name: "{{ tpa_single_node_trustification_image }}"

- name: Pull Guac image from registry.redhat.io
  when: rhel
  containers.podman.podman_image:
    name: "{{ tpa_single_node_guac_image }}"
