- name: Trustification
  hosts: trustification
  vars:
    # V2.0.0
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel:6fc55576340eb6bd6e665b0576a385cba87c0224 # noqa yaml[line-length]
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
