- name: Trustification
  hosts: trustification
  vars:
    # V1.2.1 temporary
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel9:535953dce87a04c9e881a345349df7cd2cf296c7 # noqa yaml[line-length]
    tpa_single_node_guac_image: registry.redhat.io/rhtpa/rhtpa-guac-rhel9:575848246e9b9b4997b5105abf7404cddc25d52b
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
