- name: Trustification
  hosts: trustification
  vars:
    # V1.2.2
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel9:6d13650b5c7106e1c8707db09a1a324a8e82824c # noqa yaml[line-length]
    tpa_single_node_guac_image: registry.redhat.io/rhtpa/rhtpa-guac-rhel9:58420b18ec17acc04afe239e1cd6fc038ef7a21a
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
