- name: Trustification
  hosts: trustification
  vars:
    # V1.2.0
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel9:5f4dd4a048a212bdb17eedf6613af80df227efd1 # noqa yaml[line-length]
    tpa_single_node_guac_image: registry.redhat.io/rhtpa/rhtpa-guac-rhel9:7adca20ee17df2d863354c1861b31f47948d8839
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
