- name: Deploy vexination-indexer
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: vexination-indexer
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/vexination/indexer/Deployment.yaml.j2') | from_yaml }}"
