---
- name: Set OIDC variable
  ansible.builtin.set_fact:
    oidc: keycloak

- name: Overwrite OIDC variable
  ansible.builtin.set_fact:
    oidc: cognito
  when: "'cognito' in (tpa_single_node_oidc_issuer_url | string | safe)"

- name: Check OIDC Walker is defined
  ansible.builtin.assert:
    that:
      - tpa_single_node_oidc_provider_client_id is defined
      - tpa_single_node_oidc_provider_client_id != ""
      - tpa_single_node_oidc_provider_client_secret is defined
      - tpa_single_node_oidc_provider_client_secret != ""
      - tpa_single_node_oidc_frontend_id is defined
      - tpa_single_node_oidc_frontend_id != ""
    fail_msg: OIDC FrondEnd, Walker ID and Secret is not defined

- name: Generate OIDC secret manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/infra/Secret-oidc.yaml.j2"
    dest: "{{ tpa_single_node_oidc_secret }}"
    mode: "0600"

- name: Apply storage secret manifest
  containers.podman.podman_play:
    kube_file: "{{ tpa_single_node_oidc_secret }}"
    state: started
