---
- name: Set OIDC variable
  ansible.builtin.set_fact:
    oidc: keycloak

- name: Overwrite OIDC variable
  ansible.builtin.set_fact:
    oidc: cognito
  when: "'cognito' in (tpa_single_node_oidc_issuer_url | string | safe)"

- name: Check OIDC Walker is defined
  ansible.builtin.assert:
    that:
      - tpa_single_node_oidc_provider_client_id_secret is defined
      - tpa_single_node_oidc_provider_client_id_secret != ""
    fail_msg: OIDC Walker Secret is not defined

- name: Generate OIDC auth ConfigMap manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/infra/Configmap-{{ oidc }}.yaml.j2"
    dest: "{{ tpa_single_node_oidc_configmap }}"
    mode: "0600"
  register: configmap_result

- name: Retrieve the checksum of the ConfigMap
  ansible.builtin.stat:
    path: "{{ tpa_single_node_oidc_configmap }}"
    checksum_algorithm: sha256
  register: configmap_checksum
