---
- name: Create private key (RSA, 4096 bits) for collectsub
  community.crypto.openssl_privatekey:
    path: "{{ tpa_single_node_certs_dir }}/guac-collectsub-certificate.key"

- name: Create simple self-signed certificate for collectsub
  community.crypto.x509_certificate:
    path: "{{ tpa_single_node_certs_dir }}/guac-collectsub-certificate.pem"
    privatekey_path: "{{ tpa_single_node_certs_dir }}/guac-collectsub-certificate.key"
    provider: selfsigned

- name: Copy Guac collectsub secret manifest
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/manifests/guac/collectsub/020-Secret.yaml"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/Guac-Collectsub-Secret.yaml"
    mode: "0600"

- name: Play Guac collectsub secret manifest
  containers.podman.podman_play:
    kube_file: "{{ tpa_single_node_kube_manifest_dir }}/Guac-Collectsub-Secret.yaml"
    state: started

- name: Copy Guac collectsub deployment manifest
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/manifests/guac/collectsub/030-Deployment.yaml"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/Guac-Collectsub-Deployment.yaml"
    mode: "0600"

- name: Play Guac collectsub deployment manifest
  containers.podman.podman_play:
    kube_file: "{{ tpa_single_node_kube_manifest_dir }}/Guac-Collectsub-Deployment.yaml"
    state: started
    network: "{{ tpa_single_node_podman_network }}"
