---
- name: Generate Guac csub secret manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/guac/collectsub/Secret.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/Guac-Collectsub-Secret.yaml"
    mode: "0600"

- name: Play Guac csub secret manifest
  containers.podman.podman_play:
    kube_file: "{{ tpa_single_node_kube_manifest_dir }}/Guac-Collectsub-Secret.yaml"
    state: started

- name: Deploy guac-collectsub Pod
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: guac-collectsub
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/guac/collectsub/Deployment.yaml') | from_yaml }}"
