---
- name: Confirmed required parameters provided
  ansible.builtin.assert:
    that:
      - tpa_single_node_base_hostname is defined
      - tpa_single_node_base_hostname | trim | length > 0
    msg: "'tpa_single_node_base_hostname' must be specified"

- name: Get RHTPA network details
  containers.podman.podman_network:
    name: "{{ tpa_single_node_podman_network }}"
  register: tpa_podman_network_results

- name: Set DNS Resolver
  ansible.builtin.set_fact:
    dns_resolver: "{{ tpa_podman_network_results.network.subnets[0].gateway }}"

- name: Creates a v11y walker cron file under /etc/cron.d # 0 1 * * *
  ansible.builtin.cron:
    name: v11y cronjob
    cron_file: v11-walker
    hour: "1"
    minute: "0"
    user: root
    job: "{{ lookup('ansible.builtin.template', 'configs/v11y_cronjob.sh') }}"
    state: present

- name: Deploy v11walker Pod
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: stopped
      systemd_file: v11y-walker
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/v11y/walker/Deployment.yaml') | from_yaml }}"
