---
- name: Confirmed required parameters provided
  ansible.builtin.assert:
    that:
      - tpa_single_node_base_hostname is defined
      - tpa_single_node_base_hostname | trim | length > 0
    msg: "'tpa_single_node_base_hostname' must be specified"

- name: Get RHTPA network details
  containers.podman.podman_network:
    name: "{{ tpa_single_node_podman_network }}"
  register: tpa_podman_network_results

- name: Set OIDC variable
  ansible.builtin.set_fact:
    oidc: keycloak

- name: Overwrite OIDC variable
  ansible.builtin.set_fact:
    oidc: cognito
  when: "'cognito' in (tpa_single_node_oidc_issuer_url | string | safe)"

- name: Check S3 Access key and Secret is defined
  ansible.builtin.assert:
    that:
      - tpa_single_node_s3_access_key is defined
      - tpa_single_node_s3_access_key != ""
      - tpa_single_node_s3_secret_key is defined
      - tpa_single_node_s3_secret_key != ""
    fail_msg: S3 Access Key and Secret is not defined

- name: Create S3 Storage Secret
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: v11y-api-secret-s3
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'templates/manifests/v11y/api/v11y-api-secret-s3.yaml') | from_yaml }}"

- name: Check OIDC Walker is defined
  ansible.builtin.assert:
    that:
      - tpa_single_node_oidc_walker_secret is defined
      - tpa_single_node_oidc_walker_secret != ""
    fail_msg: OIDC Walker Secret is not defined

- name: Create OIDC walker Secret
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: v11y-api-secret-oidc
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'templates/manifests/v11y/api/v11y-api-secret-oidc.yaml') | from_yaml }}"

- name: Deploy v11y-api ConfigMap
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: v11y-api-cm
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'templates/manifests/v11y/api/v11y-api-cm-' + oidc + '.yaml') | from_yaml }}"

- name: Retrieve the checksum of the ConfigMap
  ansible.builtin.stat:
    path: "{{ 'templates/manifests/v11y/api/v11y-api-cm-' + oidc + '.yaml' }}"
    checksum_algorithm: sha256
  register: cm_checksum

- name: Find the deployment temp file exists
  ansible.builtin.stat:
    path: "v11y-api-temp-deployment.yaml"
  register: temp_deployment

- name: Remove the existing temp deployment file
  ansible.builtin.file:
    path: "v11y-api-temp-deployment.yaml"
    state: absent
  when: temp_deployment.stat.exists

- name: Create temp deployment file
  ansible.builtin.template:
    src: "templates/manifests/v11y/api/v11y-api-deployment.yaml"
    dest: "v11y-api-temp-deployment.yaml"
    mode: "0755"

- name: Update minio Endpoint if needed
  ansible.builtin.blockinfile:
    path: "v11y-api-temp-deployment.yaml"
    insertafter: EOF
    block: |
            - name: STORAGE_ENDPOINT
              value: {{ tpa_single_node_s3_minio_endpoint }}
  when: "'cognito' not in oidc"

- name: Deploy v11y-api Deployment
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: v11y-api
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'v11y-api-temp-deployment.yaml') | from_yaml }}"
