- name: Create configmap for spog-api
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/infra/Configmap-ui.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-config.yaml"
    mode: "0600"
  register: configmap_spog_ui_config

- name: Retrieve the checksum of the Spog api ConfigMap
  ansible.builtin.stat:
    path: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-config.yaml"
    checksum_algorithm: sha256
  register: spog_ui_configmap_checksum

- name: Create configmap auth for collector-osv
  ansible.builtin.include_tasks: infra/component_auth.yml
  vars:
    component:
      name: "spog"
      type: "api"

- name: Generate Persistent Volume Claim for spog-api
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/spog/api/PersistentVolumeClaim.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/PVCs/spog-api.yaml"
    mode: "0600"

- name: Create persistent volume for spog-api
  ansible.builtin.command:
    cmd: "podman kube play {{ tpa_single_node_kube_manifest_dir }}/PVCs/spog-api.yaml"
  changed_when: false

- name: Deploy spog-api
  ansible.builtin.include_tasks: install_service.yml
  vars:
    specs:
      service: spog-api
      state: restarted
      network: "{{ tpa_single_node_podman_network }}"
      kube_file: "{{ role_path }}/templates/systemd/default.kube.j2"
      manifest_file: "{{ role_path }}/templates/manifests/spog/api/Deployment.yaml.j2"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-api.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-config.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
      configmap_changed: "{{ oidc_configmap_result.changed or configmap_spog_ui_config.changed }}"
