---
- name: Generate nginx secret manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/nginx/Secret.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/nginx-Secret.yaml"
    mode: "0600"
  vars:
    tpa_single_node_nginx_tls_cert_pem: "{{ lookup('file', tpa_single_node_nginx_tls_cert_pem_path) }}"
    tpa_single_node_nginx_tls_cert_key: "{{ lookup('file', tpa_single_node_nginx_tls_cert_key_path) }}"

- name: Play spog-api secret manifest
  ansible.builtin.command:
    cmd: "podman kube play {{ tpa_single_node_kube_manifest_dir }}/nginx-Secret.yaml"
  changed_when: true

- name: Create configmap for nginx
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/nginx/Configmap.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/Configmap-nginx.yaml"
    mode: "0600"

- name: Deploy nginx reverse proxy
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: nginx
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/nginx/Deployment.yaml.j2') | from_yaml }}"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/Configmap-nginx.yaml"
