---
- name: Create configmap for spog-ui-backend
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/spog/ui/Configmap-backend.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-backend.yaml"
    mode: "0600"
  register: configmap_spog_ui_backend

- name: Retrieve the checksum of the spog-ui-backend
  ansible.builtin.stat:
    path: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-backend.yaml"
    checksum_algorithm: sha256
  register: spog_ui_backend_configmap_checksum

- name: Create configmap for spog-ui-branding
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/spog/ui/Configmap-branding.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-branding.yaml"
    mode: "0600"
  register: configmap_spog_ui_branding

- name: Retrieve the checksum of the spog-ui-branding
  ansible.builtin.stat:
    path: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-branding.yaml"
    checksum_algorithm: sha256
  register: spog_ui_branding_configmap_checksum

- name: Deploy spog-ui
  ansible.builtin.include_tasks: install_service.yml
  vars:
    specs:
      service: spog-ui
      state: restarted
      network: "{{ tpa_single_node_podman_network }}"
      kube_file: "{{ role_path }}/templates/systemd/default.kube.j2"
      manifest_file: "{{ role_path }}/templates/manifests/spog/ui/Deployment.yaml.j2"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-backend.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/spog-ui-branding.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
