---
- name: Deploy guac-graphql Pod
  ansible.builtin.include_tasks: install_service.yml
  vars:
    specs:
      service: guac-graphql
      state: restarted
      network: "{{ tpa_single_node_podman_network }}"
      kube_file: "{{ role_path }}/templates/systemd/default.kube.j2"
      manifest_file: "{{ role_path }}/templates/manifests/guac/graphql/Deployment.yaml.j2"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
