---
- name: Create configmap auth for v11y-api
  ansible.builtin.include_tasks: infra/component_auth.yml
  vars:
    component:
      name: "v11y"
      type: "api"

- name: Deploy v11y-api
  ansible.builtin.include_tasks: install_service.yml
  vars:
    specs:
      service: v11y-api
      state: restarted
      network: "{{ tpa_single_node_podman_network }}"
      kube_file: "{{ role_path }}/templates/systemd/default.kube.j2"
      manifest_file: "{{ role_path }}/templates/manifests/v11y/api/Deployment.yaml.j2"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/v11y-api.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
      configmap_changed: oidc_configmap_result.changed
