---
- name: Deploy v11y walker Pod
  ansible.builtin.include_tasks: install_service.yml
  when: not tpa_single_node_v11y_walker_suspended
  vars:
    specs:
      service: v11y-walker
      state: stopped
      network: "{{ tpa_single_node_podman_network }}"
      kube_file: "{{ role_path }}/templates/systemd/default.kube.j2"
      manifest_file: "{{ role_path }}/templates/manifests/v11y/walker/Deployment.yaml.j2"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
      timer:
        type: monotonic # realtime
        pattern: 1h # *:0/10 for realtime instead of monotonic
