---
- name: Deploy v11y walker Pod
  ansible.builtin.include_tasks: install_manifest_cronjob.yml
  when: not tpa_single_node_v11y_walker_suspended
  vars:
    podman_spec:
      state: stopped
      systemd_file: v11y-walker
      timer_type: monotonic # realtime
      time_pattern: 1h # *:0/10 for realtime instead of monotonic
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/v11y/walker/Deployment.yaml.j2') | from_yaml }}"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
