---
- name: Create configmap for collectorist api
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/collectorist/api/Configmap.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/collectorist-api-guac.yaml"
    mode: "0600"
  register: collectorist_api_configmap_result

- name: Create configmap auth for collector-osv
  ansible.builtin.include_tasks: infra/component_auth.yml
  vars:
    component:
      name: "collector"
      type: "osv"

- name: Deploy collector-osv
  ansible.builtin.include_tasks: install_service.yml
  vars:
    specs:
      service: collector-osv
      state: restarted
      network: "{{ tpa_single_node_podman_network }}"
      kube_file: "{{ role_path }}/templates/systemd/default.kube.j2"
      manifest_file: "{{ role_path }}/templates/manifests/collector/osv/Deployment.yaml.j2"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/collector-osv.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/collectorist-api-guac.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
      configmap_changed: "{{ oidc_configmap_result.changed or collectorist_api_configmap_result.changed }}"
