---
- name: Create configmap for collectorist api
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/collectorist/api/Configmap.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/collectorist-api-guac.yaml"
    mode: "0600"
  register: collectorist_api_configmap_result

- name: Create configmap auth for collectorist-api
  ansible.builtin.include_tasks: infra/component_auth.yml
  vars:
    component:
      name: "collectorist"
      type: "api"

- name: Generate Persistent Volume Claim for collectorist-api
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/collectorist/api/PersistentVolumeClaim.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/PVCs/collectorist-api.yaml"
    mode: "0600"

- name: Create persistent volume for collectorist-api
  ansible.builtin.command:
    cmd: "podman kube play {{ tpa_single_node_kube_manifest_dir }}/PVCs/collectorist-api.yaml"
  changed_when: true

- name: Deploy collectorist-api
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: collectorist-api
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/collectorist/api/Deployment.yaml.j2') | from_yaml }}"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/collectorist-api.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/collectorist-api-guac.yaml"
      configmap_changed: "{{ oidc_configmap_result.changed or collectorist_api_configmap_result.changed }}"
