name: Run ansible-lint
on:
  push:
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install -r testing-requirements.txt
          ansible-galaxy install -r requirements.yml
          make lint
          make galaxy-importer-test
          # ensure that the role README was regenerated
          make role-readme
          if ! git diff --exit-code roles/tpa_single_node/README.md; then
            echo "roles/tpa_single_node/README.md not regenerated, please run 'make role-readme'"
            exit 1
          fi
